// `just boot on|off|status` — start the Large File Bridge web app at every login, on any of the three
// platforms.
//
// WHY THIS FILE EXISTS. The recipe used to write a launchd plist inline in the justfile, with
// `/opt/homebrew/bin/just` and `/opt/homebrew/bin/node` baked in as string constants. That is a macOS
// answer twice over: `launchctl` does not exist on Linux or Windows, and neither does Homebrew. So
// `just boot on` on any other machine wrote a plist nobody would ever read and reported success.
//
// One job, three schedulers — the same split the app's own workers make in
// `code/packages/backend/src/modules/schedule/os/` (launchd.ts / schtasks.ts / systemd.ts), and the
// per-platform gotchas recorded there apply here verbatim:
//
//   macOS   → a LaunchAgent under ~/Library/LaunchAgents, bootstrapped into the GUI domain.
//   Windows → a Task Scheduler task with a LogonTrigger, whose action is a hidden .vbs (a console action
//             would flash a window at every login), registered from UTF-16LE XML.
//   Linux   → a systemd USER unit wanted by default.target (never a system unit — this runs as you, with
//             your files and your git credentials).
//
// What starts is `node scripts/dev/dev.mjs boot-run`, not `just run`: `just` need not be on a login
// session's PATH, and the node binary that is running right now is a path we can record exactly.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { bootErrLog, bootLabel, bootOutLog, devDir, ensureDir, repoRoot, stateDir } from "./paths.mjs";
import { isWindows } from "./proc.mjs";

const entry = path.join(devDir, "dev.mjs");

/**
 * The node binary to record — one that SURVIVES A RUNTIME UPGRADE. Same reasoning, and the same Windows
 * carve-out, as `stableNodeBin()` in modules/schedule/schedule.service.ts: `process.execPath` under a
 * version manager is `…/26.4.0/bin/node`, a path the next upgrade deletes, and a login job whose
 * interpreter is missing fails silently at every boot.
 */
export function stableNodeBin(execPath = process.execPath) {
  if (isWindows) return execPath;
  let real;
  try {
    real = fs.realpathSync(execPath);
  } catch {
    return execPath;
  }
  for (const candidate of ["/opt/homebrew/bin/node", "/usr/local/bin/node", "/usr/bin/node"]) {
    try {
      if (fs.realpathSync(candidate) === real) return candidate;
    } catch {
      // absent or dangling — try the next
    }
  }
  return execPath;
}

/** A login session starts with a thin PATH. Give the job the usual tool dirs plus node's own. */
function loginPath() {
  const dirs = [
    path.dirname(stableNodeBin()),
    "/opt/homebrew/bin",
    "/opt/homebrew/sbin",
    "/usr/local/bin",
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin",
    path.join(os.homedir(), ".local", "share", "pnpm"),
    path.join(os.homedir(), ".local", "bin"),
  ];
  return [...new Set(dirs)].join(":");
}

function run(bin, args, { check = false } = {}) {
  try {
    return execFileSync(bin, args, {
      encoding: "utf8",
      windowsHide: true,
      timeout: 20_000,
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch (e) {
    if (check) throw e;
    return null;
  }
}

function rm(file) {
  try {
    fs.rmSync(file, { force: true });
  } catch {
    /* already gone */
  }
}

// ── macOS ───────────────────────────────────────────────────────────────────────────────────────────

const plistPath = () => path.join(os.homedir(), "Library", "LaunchAgents", `${bootLabel}.plist`);
const guiDomain = () => `gui/${process.getuid?.() ?? 501}`;

export function renderPlist() {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  Large File Bridge — auto-start the web app at login/reboot.
  GENERATED by \`just boot on\` in ${repoRoot} — do not hand-edit. Remove with: just boot off
-->
<plist version="1.0">
<dict>
    <key>Label</key><string>${bootLabel}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${stableNodeBin()}</string>
        <string>${entry}</string>
        <string>boot-run</string>
    </array>
    <key>WorkingDirectory</key><string>${repoRoot}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key><string>${loginPath()}</string>
    </dict>
    <!-- The whole point: start at login, i.e. after every reboot. -->
    <key>RunAtLoad</key><true/>
    <!-- \`boot-run\` backgrounds the dev servers and returns; that is not a crash, and the surviving
         children must not be reaped when the launcher exits. -->
    <key>KeepAlive</key><false/>
    <key>AbandonProcessGroup</key><true/>
    <key>StandardOutPath</key><string>${bootOutLog()}</string>
    <key>StandardErrorPath</key><string>${bootErrLog()}</string>
</dict>
</plist>
`;
}

const macos = {
  on() {
    const file = plistPath();
    ensureDir(path.dirname(file));
    // Idempotent: re-running `on` after a port change or a repo move re-registers against the new paths.
    run("launchctl", ["bootout", `${guiDomain()}/${bootLabel}`]);
    fs.writeFileSync(file, renderPlist());
    run("plutil", ["-lint", file]);
    run("launchctl", ["bootstrap", guiDomain(), file], { check: true });
    return file;
  },
  off() {
    run("launchctl", ["bootout", `${guiDomain()}/${bootLabel}`]);
    rm(plistPath());
  },
  state() {
    if (run("launchctl", ["print", `${guiDomain()}/${bootLabel}`]) !== null) return "on";
    return fs.existsSync(plistPath()) ? "stale" : "off";
  },
  where: () => plistPath(),
};

// ── Windows ─────────────────────────────────────────────────────────────────────────────────────────

const taskName = `\\LargeFileBridge\\${bootLabel}`;
const shimFile = () => path.join(stateDir(), "workers", `${bootLabel}.vbs`);
const taskXmlFile = () => path.join(stateDir(), "workers", `${bootLabel}.task.xml`);

function systemBin(name) {
  const root = process.env.SystemRoot || process.env.windir || "C:\\Windows";
  return path.win32.join(root, "System32", name);
}

function writeUtf16(file, body) {
  // UTF-16LE with a BOM is a hard requirement for `schtasks /Create /XML`, and for the .vbs it is what
  // lets a path under a non-ASCII user name (C:\Users\José\…) survive the console code page.
  ensureDir(path.dirname(file));
  fs.writeFileSync(file, Buffer.from(`\ufeff${body}`, "utf16le"));
}

/**
 * The hidden launcher. `WScript.Shell.Run` has no redirection of its own, so it builds ONE command line
 * and hands it to cmd — `/d` skips a user's AutoRun registry script, `/s` strips exactly the outer quote
 * pair. Window style 0 = hidden, so nothing flashes on the desktop at login.
 */
export function renderShim() {
  return [
    `' Large File Bridge web-app autostart — GENERATED by 'just boot on'. Do not edit.`,
    `' lfb-node: ${stableNodeBin()}`,
    `' lfb-entry: ${entry}`,
    `Dim q, c`,
    `q = Chr(34)`,
    `c = q & "${stableNodeBin()}" & q & " " & q & "${entry}" & q & " boot-run"`,
    `c = c & " >>" & q & "${bootOutLog()}" & q & " 2>>" & q & "${bootErrLog()}" & q`,
    `c = q & "${systemBin("cmd.exe")}" & q & " /d /s /c " & q & c & q`,
    `CreateObject("WScript.Shell").Run c, 0, False`,
    ``,
  ].join("\r\n");
}

const xmlEscape = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

export function renderTaskXml() {
  const args = `//B //Nologo "${shimFile()}"`;
  return `<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Author>Large File Bridge</Author>
    <Description>Starts the Large File Bridge web app when you log in. Generated by 'just boot on'.</Description>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <Delay>PT15S</Delay>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <Enabled>true</Enabled>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <AllowHardTerminate>true</AllowHardTerminate>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Hidden>false</Hidden>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <IdleSettings><StopOnIdleEnd>false</StopOnIdleEnd><RestartOnIdle>false</RestartOnIdle></IdleSettings>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>${xmlEscape(systemBin("wscript.exe"))}</Command>
      <Arguments>${xmlEscape(args)}</Arguments>
    </Exec>
  </Actions>
</Task>
`;
}

const queryTaskXml = () => run(systemBin("schtasks.exe"), ["/Query", "/TN", taskName, "/XML"]);

const windows = {
  on() {
    writeUtf16(shimFile(), renderShim());
    writeUtf16(taskXmlFile(), renderTaskXml());
    run(systemBin("schtasks.exe"), ["/Create", "/TN", taskName, "/XML", taskXmlFile(), "/F"]);
    // VERIFY. `schtasks` is chatty and returns non-zero for benign cases, so its failures are swallowed
    // above — which means a rejected registration would otherwise leave the shim on disk and this recipe
    // reporting success over a Task Scheduler that has never heard of us. Same check, same reason, as
    // `install()` in modules/schedule/os/schtasks.ts.
    if (queryTaskXml() === null) {
      rm(shimFile());
      throw new Error(
        `Task Scheduler did not register ${taskName} — the web app will NOT start at login (definition kept at ${taskXmlFile()})`,
      );
    }
    return taskName;
  },
  off() {
    run(systemBin("schtasks.exe"), ["/Delete", "/TN", taskName, "/F"]);
    rm(shimFile());
    rm(taskXmlFile());
  },
  state() {
    const xml = queryTaskXml();
    if (xml === null) return fs.existsSync(shimFile()) ? "stale" : "off";
    // `<Settings><Enabled>` is the language-neutral answer; `/FO LIST` prints a LOCALIZED status.
    const settings = /<Settings>([\s\S]*?)<\/Settings>/.exec(xml);
    const enabled = settings ? !/<Enabled>\s*false\s*<\/Enabled>/i.test(settings[1]) : true;
    return enabled ? "on" : "stale";
  },
  where: () => `${taskName} (launcher ${shimFile()})`,
};

// ── Linux (systemd user unit) ───────────────────────────────────────────────────────────────────────

const unitName = `${bootLabel}.service`;
const unitDir = () => path.join(process.env.XDG_CONFIG_HOME || path.join(os.homedir(), ".config"), "systemd", "user");
const unitFile = () => path.join(unitDir(), unitName);

function systemctlBin() {
  for (const candidate of ["/usr/bin/systemctl", "/bin/systemctl", "/usr/local/bin/systemctl"]) {
    try {
      fs.accessSync(candidate, fs.constants.X_OK);
      return candidate;
    } catch {
      // next
    }
  }
  return null;
}

/** systemd's own "was this machine booted with systemd" check — `sd_booted(3)`. */
function systemdAvailable() {
  return systemctlBin() !== null && fs.existsSync("/run/systemd/system");
}

/**
 * WHY RemainAfterExit + KillMode=process, and why they are not optional here. `boot-run` starts the dev
 * servers in a DETACHED launcher and returns. A oneshot unit deactivates the moment ExecStart exits, and
 * the default KillMode (control-group) then SIGTERMs everything left in the unit's cgroup — our launcher
 * included, a second after it started. RemainAfterExit keeps the unit active so that never happens, and
 * KillMode=process stops a later `systemctl --user stop` from reaching the surviving app either.
 * Together they are the systemd spelling of launchd's AbandonProcessGroup, and they preserve the same
 * contract: turning boot OFF does not stop a running app — `just stop` does.
 */
export function renderUnit() {
  return `# Large File Bridge — start the web app at login.
# GENERATED by 'just boot on' in ${repoRoot} — do not hand-edit. Remove with: just boot off
[Unit]
Description=Large File Bridge web app
After=default.target

[Service]
# oneshot + RemainAfterExit + KillMode=process: the app runs in a detached launcher this unit must not
# reap when ExecStart returns (see renderUnit() in scripts/dev/boot.mjs).
Type=oneshot
RemainAfterExit=yes
KillMode=process
WorkingDirectory=${repoRoot}
Environment=PATH=${loginPath()}
ExecStart="${stableNodeBin()}" "${entry}" boot-run
StandardOutput=append:${bootOutLog()}
StandardError=append:${bootErrLog()}

[Install]
WantedBy=default.target
`;
}

const linux = {
  on() {
    const systemctl = systemctlBin();
    if (!systemdAvailable()) {
      throw new Error(
        "This Linux machine is not running systemd (no /run/systemd/system, or no systemctl), so there is no\n" +
          "  user-session service manager to register with. Start the app yourself with: just run",
      );
    }
    ensureDir(unitDir());
    fs.writeFileSync(unitFile(), renderUnit());
    // systemd serves the OLD unit until it is told to re-read them.
    run(systemctl, ["--user", "daemon-reload"]);
    run(systemctl, ["--user", "enable", "--now", unitName], { check: true });
    return unitFile();
  },
  off() {
    const systemctl = systemctlBin();
    if (systemctl) {
      run(systemctl, ["--user", "disable", "--now", unitName]);
    }
    rm(unitFile());
    if (systemctl) run(systemctl, ["--user", "daemon-reload"]);
  },
  state() {
    const systemctl = systemctlBin();
    if (!systemctl) return fs.existsSync(unitFile()) ? "stale" : "off";
    const enabled = (run(systemctl, ["--user", "is-enabled", unitName]) || "").trim();
    if (enabled === "enabled") return "on";
    return fs.existsSync(unitFile()) ? "stale" : "off";
  },
  where: () => unitFile(),
};

// ── the platform's answer ───────────────────────────────────────────────────────────────────────────

function impl() {
  if (process.platform === "darwin") return macos;
  if (isWindows) return windows;
  if (process.platform === "linux") return linux;
  return null;
}

/** "on" | "stale" (registered artifact present but the OS is not running it) | "off" | "unsupported". */
export function bootState() {
  const os_ = impl();
  return os_ ? os_.state() : "unsupported";
}

export function bootWhere() {
  const os_ = impl();
  return os_ ? os_.where() : "(no login-startup mechanism on this platform)";
}

export function bootOn() {
  const os_ = impl();
  if (!os_) throw new Error(`No login-startup mechanism is known for platform "${process.platform}".`);
  return os_.on();
}

export function bootOff() {
  const os_ = impl();
  if (!os_) return;
  os_.off();
}

/** One line for `just status`, phrased the same way on every platform. */
export function bootStatusLine() {
  switch (bootState()) {
    case "on":
      return "boot at reboot    ON  (just boot off to disable)";
    case "stale":
      return "boot at reboot    registered but NOT active — re-run: just boot on";
    case "unsupported":
      return `boot at reboot    unsupported on ${process.platform}`;
    default:
      return "boot at reboot    OFF (just boot on to enable)";
  }
}
